using System;
using Week1;
using Week3.FactoryMethod_Pattern;
using Week4.People;
using Week5.People;
using Week6.People;

//Week 6 Exercise: Concrete Factory -> Composite Alumno Factory

namespace Week6.FactoryMethod_Pattern
{
    /// <summary>
    /// A concrete factory that implements the <see cref="MyComparableFactory"/> to create <see cref="CompositeAlumno"/> instances. 
    /// </summary>
    /// <remarks>
    /// Encapsulates the logic for creating <see cref="CompositeAlumno"/> instances either throug automated random generation or manual keyboard input.
    /// </remarks>
    public class CompositeAlumnoFactory : MyComparableFactory
    {
        /// <summary>
        /// Creates a new <see cref="CompositeAlumno"/> with the option to choose the <see cref="IAlumno"/> type for each child, whose attributes are generated automatically at random.
        /// </summary>
        /// <returns>A concrete <see cref="CompositeAlumno"/> as an <see cref="IMyComparable"/>.</returns>
        public override IMyComparable RandomCreate()
        {
            return this.CreateComposite(1);
        }

        /// <summary>
        /// Creates a new <see cref="CompositeAlumno"/> with the option to choose the <see cref="IAlumno"/> type for each child, whose attributes are generated by manual keyboard input.
        /// </summary>
        /// <returns>A concrete <see cref="CompositeAlumno"/> as an <see cref="IMyComparable"/>.</returns>
        public override IMyComparable KeyboardCreate()
        {
            return this.CreateComposite(2);
        }

        /// <summary>
        /// Creates the <see cref="CompositeAlumno"/> instance manually or randomly bassed on the selected option.
        /// </summary>
        /// <param name="selection">The selected option that signals a manual or random creation. ( 1: Random , 2: Manual ).</param>
        /// <returns>A instance of <see cref="CompositeAlumno"/> with 5 <see cref="IAlumno"/> children.</returns>
        private CompositeAlumno CreateComposite(int selection)
        {
            Console.WriteLine("\n---Creating Composite Alumno---\n");
            CompositeAlumno composite = new CompositeAlumno();
            for (int i = 0; i<5; i++)
            {
                int option = this.ComproveOption();
                IAlumno alumno = null;
                switch (selection)
                {
                    case 1:
                        alumno = (IAlumno)MyComparableFactory.RandomCreate(option);
                        break;
                    case 2:
                        alumno = (IAlumno)MyComparableFactory.KeyboardCreate(option);
                        break;
                }
                composite.Add(alumno);
                Console.WriteLine("Alumno created");
            }
            Console.WriteLine("\n---Composite Alumno created---\n");
            return composite;
        }

        /// <summary>
        /// Comproves the concrete factory option to ensure the type selected is an <see cref="IAlumno"/>.
        /// </summary>
        /// <returns>An <see cref="int"/> that is the concrete factory option.</returns>
        private int ComproveOption()
        {
            bool correct = false;
            int option = 2;
            while (!correct)
            {
                Console.Write("\nDifferent Alumno types for the Composite:\n2 -> Alumno\n4 -> Diligent Alumno\n5 -> Alumno Decorated\n6 -> Diligent Alumno Decorated\n7 -> Alumno Proxy\n8 -> Alumno Composite\nIntroduce the Alumno type: ");
                option = base._read.KeyboardNumber();
                if (option == 2 || option == 4 || option == 5 || option == 6 || option == 7 || option == 8)
                {
                    correct = true;
                    break;
                }
                Console.WriteLine("\nIncorrect Alumno Option");
            }
            return option;
        }
    }
}
